spring.application.name=youtube

spring.datasource.url=jdbc:postgresql://localhost:5432/kunuz
spring.datasource.username=quvoncuz
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

########################
#         ATTACH
########################
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
attach.dir=attaches

###########
# Fly-Way
###########
spring.flyway.enabled=false
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=0

##########
# Email Sender
##########
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=quvoncuz@mail.ru
spring.mail.password=SGBgdtJFanC8nd6q8ujF
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000